on:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest # give me a new machine with ubuntu latest version
    steps:
      # 1. Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 20
          cache: 'npm'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run unit tests
      - name: Run unit tests
        run: npm test

      # 5. Build Docker image
      - name: Build Docker image
        run: docker build -t express-hello-world:${{ github.sha }} .

      - name: Save Docker image to tar archive
        run: |
            mkdir -p image-artifact
            docker save express-hello-world:${{ github.sha }} -o image-artifact/express-hello-world.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: docker-image
          path: image-artifact/express-hello-world.tar
          retention-days: 1

  push-to-docker-hub:
    runs-on: ubuntu-latest
    needs: test-and-build
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v8.0.1
        with:
            name: docker-image
            path: image-artifact

      - name: Load Docker image
        run: docker load -i image-artifact/express-hello-world.tar

      # Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v4.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the image to Docker Hub
      - name: Tag and Push Docker image
        run: |
                # Tag with GitHub SHA
                docker tag express-hello-world:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/express-hello-world:${{ github.sha }}
                docker push ${{ secrets.DOCKER_USERNAME }}/express-hello-world:${{ github.sha }}

                # Tag with 'latest'
                docker tag express-hello-world:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/express-hello-world:latest
                docker push ${{ secrets.DOCKER_USERNAME }}/express-hello-world:latest